# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    providers:
        db_provider:
            entity:
                class: ShagBundle:Blog\Users
                property: username

    role_hierarchy:
        ROLE_ANONYMOUS:   ROLE_ANONYMOUS
        ROLE_USER:        [ROLE_ANONYMOUS, ROLE_USER]
        ROLE_ADMIN:       [ROLE_ANONYMOUS, ROLE_USER, ROLE_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ANONYMOUS, ROLE_ADMIN, ROLE_USER, ROLE_SUPER_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            provider: db_provider
            anonymous: ~
            form_login:
                login_path: /blog/login
                check_path: /blog/login
                default_target_path: /blog/posts
                always_use_default_target_path: true
                csrf_token_generator: security.csrf.token_manager

    encoders:
        ShagBundle\Entity\Blog\Users:
            algorithm: bcrypt
            cost: 12

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/blog/, role: [IS_AUTHENTICATED_ANONYMOUSLY, ROLE_ANONYMOUS, ROLE_ADMIN, ROLE_USER, ROLE_SUPER_ADMIN] }

