<?php

namespace ShagBundle\Repository\PortFolio;

use Doctrine\ORM\EntityRepository;
use ShagBundle\Entity\PortFolio\Contact;

/**
 * UsersRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{
}
