<?php

namespace ShagBundle\Repository\PortFolio;

use Doctrine\ORM\EntityRepository;
use ShagBundle\Entity\PortFolio\Users;

/**
 * UsersRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends EntityRepository
{
    public function getLastUser()
    {
        $em = $this->getEntityManager();

        return $em
            ->getRepository(Users::class)
            ->createQueryBuilder('u')
            ->orderBy('u.id', 'DESC')
            ->setMaxResults(1)
            ->getQuery()
            ->getResult();
    }
}
